name: Build and deploy Node.js app to Azure Web App - SocialMediaApp

on:
  push:
    branches:
      - kobbe
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Upload Frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact  # Changed artifact name
          path: ./Frontend

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./Frontend

      - name: Upload build artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-artifact  # Changed artifact name
          path: ./Frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: frontend-build-artifact  # Adjusted to match new name

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'SocialMediaApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_07FD002CF02042E48821AB51CDC0804E }}
          package: .
